spring:
  ai:
    mcp:
      client:
        type: SYNC
        streamable-http:
          connections:
            countries:
              url: http://localhost:8081
        stdio:
          connections:
            weather:
              command: npx
              args:
                - tsx
                - ${WEATHER_MCP_SCRIPT}
              env:
                WEATHER_API_URL: https://api.weatherapi.com/v1/current.json
                WEATHER_API_KEY: ${WEATHER_API_KEY}
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3:4b
      embedding:
        model: mxbai-embed-large
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
  application:
    name: assistant-app
  datasource:
    url: jdbc:postgresql://localhost:5432/assistant
    username: postgres
    password: postgres
app:
  rag:
    ingestion:
      enabled: false
